# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 978a189cf9932471e15de5eee87ab6f6ece239e958272c92e02d31a0ea697d9fd1db0fc84c6d710eb49549c61ac10097e8ae475a875d4a23797413f6b3147093

test:
  secret_key_base: 4c718552ee844386f63b4bf3131aa29361f66e585d89d5b0d1a09559049e598bd53a5e32f17ad293519046891a074053de2e9e8cda9fe044e7ec4a30b9b3c353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
